version: "3"
services:
  code:
    build: .
    restart: always
    environment:
      PASSWORD: ${VSCODE_PASSWORD}
      DEFAULT_WORKSPACE: /workspace
      APP_PORT: ${APP_PORT}
      CONTEXT_PATH: ${CONTEXT_PATH}
      CODER_PROXY_TRUSTED_ORIGINS: '*'
    volumes:
      - ./code/workspace:/workspace
      - ./code/config/settings.json:/home/coder/.local/share/code-server/User/settings.json
      - ./code/config/argv.json:/home/coder/.local/share/code-server/User/argv.json
      - ./code/config/languagepacks.json:/home/coder/.local/share/code-server/languagepacks.json
      - ./code/config/eclipse-java-style.xml:/home/coder/eclipse-java-style.xml

  nginx:
    image: nginx:latest
    ports:
      - 8085:80
    environment:
      CONTEXT_PATH: ${CONTEXT_PATH}
      APP_PORT: ${APP_PORT}
    volumes:
      - ./nginx/templates:/etc/nginx/templates

  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      - POSTGRES_USER=${USER_NAME}
      - POSTGRES_PASSWORD=${USER_PASS}
    volumes:
      - ./db:/var/lib/postgresql/data
